### ISSUE TITLE
mintime / maxtime only working correctly for first 24000 ticks

### ISSUE THREAD

**Issue by Terpo** [McJtyMods/InControl#21]
AbyssalCraft-1.11.2-1.9.4-pre-2.jar
compatlayer-1.11.2-0.2.8.jar
incontrol-3.5.5.jar
mcjtylib-1.1x-2.3.11.jar

Here a potentialspawn:
  {
    "dimension": 0,
	"mindifficulty": 1.0,
	"maxlight": 4,
	"mintime": 18000,
	"seesky": true,
	"maxcount": "30,abyssalcraft:shadowcreature",
    "mobs": [
      {
        "mob": "abyssalcraft:shadowcreature",
        "weight": 5,
        "groupcountmin": 1,
        "groupcountmax": 2
      }
    ]
  }

for the spawn.json:
{
	"mob": ["abyssalcraft:shadowcreature"],
    "dimension": 0,	
	"result": "allow"
},
{
	"result": "deny"
}

Here is the problem: 
For me it seems that there is a %24000 missing somewhere.

An example
/time set 15000      --> mobs should not spawn and they do not   -> fine
/time add 24000     --> mobs should not spawn and they do -> broken 

now we add a maxtime to the potentialspawn	"maxtime": 18000, and remove the mintime
/time set 15000      --> mobs should spawn and they do -> fine
/time add 24000     --> mobs should spawn and they do not -> broken

**Comment by McJty** [comment]
Seems to be a bug in the time add command itself as that worldTime value is not allowed to go beyond 24000.

**Comment by Terpo** [comment]
ok, I started testing with:
	"mintime": 16500,
	"maxtime": 19500,
and did /time set 17000          the mobs did spawn
now I simply will let the game run by itself, results in ~20min

**Comment by Terpo** [comment]
ok, after waiting 24000 ticks I can confirm that it still does not work^^

**Comment by McJty** [comment]
That seems that MC is not following its own guidelines then. I can work around it in InControl

**Comment by Terpo** [comment]
That would be wunderful.
Ok, lets go on in this issue thread:
mobs don't seem to spawn with maxlight: 3 and seesky: true
without seesky they only spawn under trees.

Is the minimal block light 4 in the night? I was hoping that the hardcore darkness mod does set the block light to a real 0.

**Comment by McJty** [comment]
You should be able to see the actual light level with F3

**Comment by Terpo** [comment]
![2017-05-18_11 13 27](https://cloud.githubusercontent.com/assets/4256058/26195126/0b2860c8-3bbb-11e7-931e-6b6311e4a5df.png)

BL is 0 and skylight 15.

Tested with:
{
    "dimension": 0,
	"mindifficulty": 1.3,
	"maxlight": 2,
	"seesky": true,
	"angry":true,
	"maxcount": "30,minecraft:skeleton_horse",
    "mobs": [
      {
        "mob": "minecraft:skeleton_horse",
        "weight": 5,
        "groupcountmin": 1,
        "groupcountmax": 1
      }
    ]
  }

and 

{
	"mob": ["minecraft:skeleton_horse"],
    "dimension": 0,
	"result": "allow"
},
{
	"result": "deny"
}

with maxlight 4   --> spawns         with maxlight 2 ---> not a single spawn

**Comment by McJty** [comment]
Hmm can you look at the ground and take a screenshot then? Also use one of the light overlay mods which show the number (like 'F4' for LightLevelOverlay)

**Comment by Terpo** [comment]
![2017-05-18_11 30 14](https://cloud.githubusercontent.com/assets/4256058/26195847/670f0cf0-3bbd-11e7-8872-cbd40a0be06e.png)

**Comment by McJty** [comment]
Weird. No explanation for that.

**Comment by Terpo** [comment]
Just you know. I removed Hardcore Darkness to see if its a mod interaction problem. But it doesnt seem to be one. Block light stays at 0.

**Comment by McJty** [comment]
I don't see how it maxlight 2 vs 4 can make a difference is the light is 0. That doesn't make sense

**Comment by Terpo** [comment]
Its also interesting that blocklight stays at 0 when its noon^^

**Comment by Terpo** [comment]
With maxlight 1 and without seesky they spawn, but only under trees or structures. Seems there is some kind of hardcoded night sky light or something.

**Comment by TheQKnight** [comment]
I know its been like a year, but this is still happening for me too. mintime and maxtime only apply to first 24000 ticks

Edit: also happening with Fxcontrol

**Comment by McJty** [comment]
I will fix this

**Comment by McJty** [comment]
Fixed in latest version
